---
  - name: New VM
    hosts: k8s
    become: yes
    become_user: root
    gather_facts: No
    tasks:
      - name: Install a list of packages 
        yum:
          name: "{{ packages }}"
        vars:
          packages:
          - vim
          - net-tools
          - wget
          - telnet
          - git
   #### Run ansible-galaxy collection install ansible.posix        
      - name: Disable Selinux
        ansible.posix.selinux:
            policy: targeted
            state: disabled
     
      - name: Disable Firewall  
        service:
          name: firewalld
          state: stopped
          enabled: no

      - name:  Upgrade all packages
        yum:
            name: '*'
            state: latest

